### ISSUE TITLE
np.asmatrix errors

### ISSUE THREAD

**Issue by henryc-ucl** [Paul-Warburton-Research-Group/pycqed#1]
Python 3.8.8 on windows 10, numpy version 1.21.4.
`
hamil = HamilSpec(circuit,mode="node")
hamil.setTruncation(1,20,"charge")
hamil.prepareOperators()
hamil.params.getParameterNamesList()
`
raises error
ValueError: matrix must be 2-dimensional
(due to np.asmatrix)

**Comment by lfry512** [comment]
Thanks @henryc-ucl for fixing this.
Ref https://github.com/qutip/qutip/issues/1433
